// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	EXTERNAL_API_KEY: string;
	D1_DB: D1Database;
	GITHUB_TOKEN: string;
	GITHUB_BRANCH: string;
	GITHUB_BASE_API_URL: string;
}
